history = 10
history_file_path = "config/.massa_history"
timeout = 1000

[default_node]
# labnet0
# ip = "145.239.66.206"
# massa1
ip = "195.134.167.226"
# ip = "127.0.0.1"
private_port = 33034
public_port = 33035
