[package]
name = "massa_protocol_worker"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
tokio = { version = "1.20", features = ["full"] }
futures = "0.3"
tracing = "0.1"
# custom modules
massa_hash = { path = "../massa-hash" }
massa_logging = { path = "../massa-logging" }
massa_models = { path = "../massa-models" }
massa_network_exports = { path = "../massa-network-exports" }
massa_pool_exports = { path = "../massa-pool-exports" }
massa_protocol_exports = { path = "../massa-protocol-exports" }
massa_serialization = { path = "../massa-serialization" }
massa_storage = { path = "../massa-storage" }
massa_time = { path = "../massa-time" }

[dev-dependencies]
lazy_static = "1.4"
serial_test = "0.9"
futures = "0.3"

massa_signature = { path = "../massa-signature" }
massa_pool_exports = { path = "../massa-pool-exports", features = ["testing"] }
