name: CI

on:
  push:
    branches: [main, staging, trying]
  pull_request:
    branches: [main, 'testnet_*']
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTFLAGS: "--deny warnings"

jobs:
  # Quick tests on each commit/PR
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-12-24
          components: rustfmt
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "sanity"
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  
  check:
    if: github.ref != 'refs/heads/staging'
    needs: sanity
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-12-24
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "check"
      - uses: actions-rs/cargo@v1
        with:
          command: check

  clippy:
    if: github.ref != 'refs/heads/staging'
    needs: sanity
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-12-24
          components: clippy
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "clippy"
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -A clippy::uninlined-format-args


  # Full cross-platform tests required by bors to merge on main branch
  full:
    name: full
    needs: sanity
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-12-24
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "massa"
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features testing

  build: # quick hack because bors wrongly detect matrix jobs status
    needs: full
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-12-24
          components: rustfmt
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "doc"
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps
      - uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: target/doc

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: setup_tests
        shell: bash
        run: |
          cargo install cargo-script && cargo script tools/setup_test.rs && git diff --no-ext-diff --quiet
